/**
 * 共享股票数据源（单一数据源 Single Source of Truth）
 *
 * 所有页面（nav_bar.js、scorer.html、index.html等）统一引用此文件获取股票列表。
 * 新增/删除公司时，只需更新此文件 + index.html表格即可，无需修改nav_bar.js。
 *
 * 使用方式：
 *   <script src="stocks_data.js"></script>
 *   然后通过 window.STOCKS_DATA 或 STOCKS_DATA 访问数组
 */
(function() {
    var stocks = [
        {code:'AAPL',name:'苹果公司',href:'aapl.html'},
        {code:'MSFT',name:'微软公司',href:'msft.html'},
        {code:'GOOG',name:'Alphabet/Google - 互联网搜索..',href:'goog.html'},
        {code:'AMZN',name:'亚马逊公司',href:'amzn.html'},
        {code:'META',name:'Meta平台公司',href:'meta.html'},
        {code:'KSPI',name:'Kaspi.kz',href:'kspi.html'},
        {code:'SUZ',name:'Suzano S.A.',href:'suz.html'},
        {code:'CALM',name:'Cal-Maine Foods',href:'calm.html'},
        {code:'PPC',name:'Pilgrim\'s Pride',href:'ppc.html'},
        {code:'RMD',name:'ResMed',href:'rmd.html'},
        {code:'MATX',name:'Matson',href:'matx.html'},
        {code:'ADT',name:'ADT Inc.',href:'adt.html'},
        {code:'PHI',name:'PLDT Inc.',href:'phi.html'},
        {code:'ACI',name:'Albertsons Companies',href:'aci.html'},
        {code:'AMP',name:'Ameriprise Financial',href:'amp.html'},
        {code:'NICE',name:'NICE Ltd.',href:'nice.html'},
        {code:'HRB',name:'H&R Block, Inc.',href:'hrb.html'},
        {code:'GIS',name:'通用磨坊',href:'gis.html'},
        {code:'MMS',name:'Maximus, Inc.',href:'mms.html'},
        {code:'MKC',name:'McCormick & Company',href:'mkc.html'},
        {code:'STNE',name:'StoneCo Ltd.',href:'stne.html'},
        {code:'MAT',name:'Mattel, Inc.',href:'mat.html'},
        {code:'INGR',name:'Ingredion Incorporated',href:'ingr.html'},
        {code:'FIS',name:'Fidelity National Infor..',href:'fis.html'},
        {code:'VIPS',name:'Vipshop Holdings Limited',href:'vips.html'},
        {code:'WU',name:'Western Union',href:'wu.html'},
        {code:'ANF',name:'Abercrombie & Fitch',href:'anf.html'},
        {code:'MNST',name:'Monster Beverage',href:'mnst.html'},
        {code:'AXP',name:'American Express',href:'axp.html'},
        {code:'V',name:'Visa Inc.',href:'v.html'},
        {code:'VST',name:'Vistra Corp.',href:'vst.html'},
        {code:'MCO',name:'Moody\'s Corporation',href:'mco.html'},
        {code:'SHW',name:'Sherwin-Williams Company',href:'shw.html'},
        {code:'SPG',name:'Simon Property Group',href:'spg.html'},
        {code:'JBS',name:'JBS S.A.',href:'jbs.html'},
        {code:'UHS',name:'Universal Health Services',href:'uhs.html'},
        {code:'KGC',name:'Kinross Gold Corporation',href:'kgc.html'},
        {code:'SYY',name:'Sysco Corporation',href:'syy.html'},
        {code:'DXCM',name:'DexCom, Inc.',href:'dxcm.html'},
        {code:'NOK',name:'Nokia Corporation',href:'nok.html'},
        {code:'CHTR',name:'Charter Communications',href:'chtr.html'},
        {code:'TLIH',name:'Ten-League Internationa..',href:'tlih.html'},
        {code:'LDOS',name:'Leidos Holdings, Inc.',href:'ldos.html'},
        {code:'LRCX',name:'Lam Research',href:'lrcx.html'},
        {code:'LAMR',name:'Lamar Advertising',href:'lamr.html'},
        {code:'IBP',name:'Installed Building Products',href:'ibp.html'},
        {code:'BX',name:'Blackstone',href:'bx.html'},
        {code:'LECO',name:'Lincoln Electric',href:'leco.html'},
        {code:'ECG',name:'Everus Construction Group',href:'ecg.html'},
        {code:'TT',name:'Trane Technologies',href:'tt.html'},
        {code:'CMCSA',name:'Comcast Corporation',href:'cmcsa.html'},
        {code:'MLI',name:'Mueller Industries, Inc.',href:'mli.html'},
        {code:'DECK',name:'Deckers Outdoor Corpora..',href:'deck.html'},
        {code:'APAM',name:'Artisan Partners Asset ..',href:'apam.html'},
        {code:'PDD',name:'PDD Holdings Inc.',href:'pdd.html'},
        {code:'VNT',name:'Vontier Corporation',href:'vnt.html'},
        {code:'SFM',name:'Sprouts Farmers Market',href:'sfm.html'},
        {code:'KTB',name:'Kontoor Brands',href:'ktb.html'},
        {code:'BKE',name:'The Buckle, Inc.',href:'bke.html'},
        {code:'NVO',name:'Novo Nordisk',href:'nvo.html'},
        {code:'CHKR',name:'Chesapeake Granite Wash..',href:'chkr.html'},
        {code:'BLBD',name:'Blue Bird Corporation',href:'blbd.html'},
        {code:'CHH',name:'Choice Hotels Internati..',href:'chh.html'},
        {code:'FTDR',name:'Frontdoor, Inc.',href:'ftdr.html'},
        {code:'MUSA',name:'Murphy USA Inc.',href:'musa.html'},
        {code:'AMAT',name:'Applied Materials',href:'amat.html'},
        {code:'KLAC',name:'KLA Corporation',href:'klac.html'},
        {code:'ASML',name:'ASML Holding',href:'asml.html'},
        {code:'AGX',name:'Argan',href:'agx.html'},
        {code:'TJX',name:'The TJX Companies - 全球最..',href:'tjx.html'},
        {code:'TSCO',name:'Tractor Supply Company',href:'tsco.html'},
        {code:'EXEL',name:'Exelixis',href:'exel.html'},
        {code:'ULTA',name:'Ulta Beauty',href:'ulta.html'},
        {code:'ZTS',name:'Zoetis - 动物保健/宠物药品疫苗/畜牧药品',href:'zts.html'},
        {code:'HESM',name:'Hess Midstream',href:'hesm.html'},
        {code:'CHKP',name:'Check Point Software',href:'chkp.html'},
        {code:'QLYS',name:'Qualys',href:'qlys.html'},
        {code:'RCI',name:'Rogers Communications',href:'rci.html'},
        {code:'ROST',name:'Ross Stores',href:'rost.html'},
        {code:'BAH',name:'Booz Allen Hamilton',href:'bah.html'},
        {code:'BR',name:'Broadridge Financial So..',href:'br.html'},
        {code:'CMG',name:'Chipotle Mexican Grill..',href:'cmg.html'},
        {code:'IT',name:'Gartner, Inc.',href:'it.html'},
        {code:'ATMU',name:'Atmus Filtration Techno..',href:'atmu.html'},
        {code:'LII',name:'Lennox International - ..',href:'lii.html'},
        {code:'IDCC',name:'InterDigital - 无线通信/视频压..',href:'idcc.html'},
        {code:'RELX',name:'RELX plc - 信息分析/决策工具',href:'relx.html'},
        {code:'EME',name:'EMCOR Group - 机电建筑与服务',href:'eme.html'},
        {code:'RACE',name:'Ferrari - 超豪华跑车/奢侈品',href:'race.html'},
        {code:'CAT',name:'Caterpillar - 全球工程机械+动力系统龙头',href:'cat.html'},
        {code:'APH',name:'Amphenol - 全球互连/连接器巨头',href:'aph.html'},
        {code:'CTAS',name:'Cintas - 企业制服租赁/设施服务/急救安全',href:'ctas.html'},
        {code:'GWW',name:'W.W. Grainger - MRO工业分销..',href:'gww.html'},
        {code:'IESC',name:'IES Holdings - 电气/技术基础设..',href:'iesc.html'},
        {code:'MANH',name:'Manhattan Associates - ..',href:'manh.html'},
        {code:'IDXX',name:'IDEXX Laboratories - 兽医..',href:'idxx.html'},
        {code:'ROL',name:'Rollins - 害虫防治/Orkin品牌/..',href:'rol.html'},
        {code:'FIX',name:'Comfort Systems USA - M..',href:'fix.html'},
        {code:'PJT',name:'PJT Partners - 精品投资银行/M&A咨询/重组',href:'pjt.html'},
        {code:'NVR',name:'NVR, Inc. - 住宅建筑/轻资产土地期权+零债务回购',href:'nvr.html'},
        {code:'SUN',name:'Sunoco LP - 燃料分销+管道+终端MLP高分红',href:'sun.html'},
        {code:'KMB',name:'Kimberly-Clark - 153年消费品防御股/股息之王53年',href:'kmb.html'},
        {code:'ITW',name:'Illinois Tool Works - 113年工业复利机器/80-20经营哲学+62年股息之王',href:'itw.html'},
        {code:'HSY',name:'好时公司 - 132年巧克力复利机器/美国糖果#1份额33.5%+Reese\'s全美销量第一+15年股息增长',href:'hsy.html'},
        {code:'BBY',name:'百思买 Best Buy - 59年消费电子零售龙头/全美CE零售#1份额33%+Geek Squad服务护城河+22年股息增长',href:'bby.html'},
        {code:'UNP',name:'联合太平洋铁路 Union Pacific - 163年钢铁脊梁/32,889英里路权不可复制+126年股息支付+10年回购缩减股本29%',href:'unp.html'},
        {code:'CDW',name:'CDW公司 - 41年IT中间商/美国IT经销商#1+25万客户+1000+品牌双边市场+连续12年股息增长+8年回购缩减股本24%',href:'cdw.html'},
        {code:'UL',name:'联合利华 Unilever - 166年消费品巨头/30个Power Brands(Dove/Hellmann\'s/Vaseline)+190国分销+2025冰淇淋分拆+聚焦美妆个护+连续50+年分红',href:'ul.html'},
        {code:'CARG',name:'CarGurus - 19年汽车版Zillow/美国#1汽车购物网站+双边市场网络效应+34409家付费经销商+毛利率93%+FCF Margin 32%+零债务+6年回购7.5亿缩减股本19%',href:'carg.html'},
        {code:'FTNT',name:'Fortinet 飞塔 - 25年网络安全龙头/全球防火墙#1(55%份额)+FortiASIC自研芯片5-10x性能优势+FortiOS统一OS+650,000+装机量+毛利率80.8%+FCF Margin 32.7%+ROE 149.8%+6年回购106.9亿美元',href:'ftnt.html'},
        {code:'PTC',name:'PTC Inc. - 40年工业软件龙头/CAD(Creo/Onshape)+PLM(Windchill/Codebeamer)+ALM+SLM(ServiceMax)全栈+30,000客户+95%经常性收入+84%软件毛利率+40%FCF Margin+数据锁定+合规锁定护城河',href:'ptc.html'}
    ];

    // 暴露为全局变量
    window.STOCKS_DATA = stocks;
    window.STOCKS_COUNT = stocks.length;
})();
